RSDK-3143 - implement cgo api calling into c for cartoFacade
viamrobotics/viam-cartographer pull request #130
Opened 2023-06-09 15:25 UTC by kim-mishra

2023-06-12 14:32 UTC, kim-mishra commented on viam-cartographer/src/carto_facade/carto_facade.h
> +#ifdef __cplusplus
@nicksanford I actually think these are C++ libraries, so they need to be within an #ifdef __cplusplus

2023-06-12 15:13 UTC, kim-mishra commented on viam-cartographer/src/carto_facade_go/carto_facade.go
> +	ppVcl := (**C.viam_carto_lib)(unsafe.Pointer(pVcl))
TODO: run `go vet` manually and confirm it passes 
TODO: check if `go vet` runs in CI and if not create a ticket to add it to CI

2023-06-13 15:28 UTC, kim-mishra commented on viam-cartographer.go
> +var ViamCartoLib, _ = cartoFacade.NewViamCartoLib(1, 1)
var ViamCartoLib TYPE_OF_THIS_THING

2023-06-13 19:27 UTC, nicksanford requested changes

2023-06-13 19:27 UTC, nicksanford commented on viam-cartographer/src/carto_facade_go/carto_facade.go
> +// Package cartofacade provides an api to call into c code
Lets change the directory structure a bit:

1. lets have all the code your created under a package called `cartofacade` 
2. this file should be moved (with the same content) to `cartofacade/cgo_api.go`

2023-06-13 19:27 UTC, nicksanford commented on viam-cartographer/src/carto_facade_queue/carto_facade_queue.go
> +package cartofacadequeue
Lets change the directory structure a bit:

1. lets have all the code your created under a package called cartofacade
2. this file should be moved (with the same content) to cartofacade/queue.go

2023-06-13 19:27 UTC, nicksanford commented on viam-cartographer.go
> +func setUpCartoFacadeQueue(cartoFacadeCancelCtx context.Context, activeBackgroundWorkers *sync.WaitGroup) cfq.CartoFacadeQueue {
Lets move this into viam-cartographer/src/carto_facade_queue/carto_facade_queue.go & make it public

2023-06-13 19:27 UTC, nicksanford commented on viam-cartographer.go
> +	cartoFacade "github.com/viamrobotics/viam-cartographer/viam-cartographer/src/carto_facade_go"
lets remove all changes to viam-cartographer.go

2023-06-13 19:27 UTC, nicksanford commented on viam-cartographer/src/carto_facade_go/carto_facade.go
> +}
```suggestion
type CartoLib struct {
	value *C.viam_carto_lib
}
```

2023-06-13 19:27 UTC, nicksanford commented on viam-cartographer/src/carto_facade_go/carto_facade.go
> +}
```suggestion
type Carto struct {
	value *C.viam_carto
}
```

2023-06-13 19:27 UTC, nicksanford commented on viam-cartographer/src/carto_facade_go/carto_facade.go
> +		// TODO: how to make this error useful?
Please write a function in this same file that converts all the error status codes (other than success) to go errors, who's message is the same as the name of the status.  Return the error derived from that function.

2023-06-13 19:27 UTC, nicksanford commented on viam-cartographer/src/carto_facade_go/carto_facade.go
> +	pVcl := C.alloc_viam_carto_lib()
please add comments for why we need to do this

2023-06-13 19:27 UTC, nicksanford commented on viam-cartographer/src/carto_facade_go/carto_facade.go
> +	ppVcl := (**C.viam_carto_lib)(unsafe.Pointer(pVcl))
1. What does this do if `pVcl` is `nil` (which happens if malloc can't allocate memory)? Do we need to check for nil before passing it it to `unsafe.Pointer`?
2.  What happens if we don't do the cast?
3. Please comment why we need to call unsafe.Pointer

2023-06-13 19:27 UTC, nicksanford commented on viam-cartographer/src/carto_facade_go/carto_facade.go
> +	ppVcl := (**C.viam_carto_lib)(unsafe.Pointer(pVcl))
what was the answer to the todos?

2023-06-13 19:27 UTC, nicksanford commented on viam-cartographer/src/carto_facade_go/carto_facade.go
> +	}
```suggestion
	if err := statusErr(status), err != nil {
		return CViamCartoLib{}, err
	}
```

2023-06-13 19:27 UTC, nicksanford commented on viam-cartographer/src/carto_facade_go/carto_facade.go
> +	if !successfulStatus(status) {
please replace with `statusErr(status)`

2023-06-13 19:27 UTC, nicksanford commented on viam-cartographer/src/carto_facade_go/carto_facade.go
> +func getConfig() C.viam_carto_config {
lets actually build out this function such that it is usable i.e. it takes a config, validates & if valid, returns the C type.

2023-06-13 19:27 UTC, nicksanford commented on viam-cartographer/src/carto_facade_go/carto_facade.go
> +func NewViamCarto(vcl CViamCartoLib) (CViamCarto, error) {
Lets have this function actually take the viam-cartographer config & convert it into the appropriate C type

2023-06-13 19:27 UTC, nicksanford commented on viam-cartographer/src/carto_facade_go/carto_facade.go
> +	defer cleanConfig(vcc)
```suggestion
	defer C.free_bstring_array(vcc.sensors)
```

2023-06-13 19:27 UTC, nicksanford commented on viam-cartographer/src/carto_facade_go/carto_facade.go
> +}
```suggestion
```

2023-06-13 19:27 UTC, nicksanford commented on viam-cartographer/src/carto_facade_go/carto_facade.go
> +	if !successfulStatus(status) {
please replace with `statusErr(status)`

2023-06-13 19:27 UTC, nicksanford commented on viam-cartographer/src/carto_facade_go/carto_facade.go
> +	if !successfulStatus(status) {
please replace with `statusErr(status)`

2023-06-13 19:27 UTC, nicksanford commented on viam-cartographer/src/carto_facade_go/carto_facade.go
> +	if !successfulStatus(status) {
please replace with `statusErr(status)`

2023-06-13 19:27 UTC, nicksanford commented on viam-cartographer/src/carto_facade_go/carto_facade.go
> +	if !successfulStatus(status) {
please replace with `statusErr(status)`

2023-06-13 19:27 UTC, nicksanford commented on viam-cartographer/src/carto_facade_go/carto_facade.go
> +func (vc *CViamCarto) AddSensorReading(ctx context.Context) error {
Lets have this function actually take a lidar reading (probably a byte slice) & a timestamp & convert it into the appropriate C type.

2023-06-13 19:27 UTC, nicksanford commented on viam-cartographer/src/carto_facade_go/carto_facade.go
> +	if !successfulStatus(status) {
please replace with `statusErr(status)`

2023-06-13 19:27 UTC, nicksanford commented on viam-cartographer/src/carto_facade_go/carto_facade.go
> +	if !successfulStatus(status) {
please replace with `statusErr(status)`

2023-06-13 19:27 UTC, nicksanford commented on viam-cartographer/src/carto_facade_go/carto_facade.go
> +}
```suggestion
type CartoGetPositionResponse struct {
	value C.viam_carto_get_position_response
}
```

2023-06-13 19:27 UTC, nicksanford commented on viam-cartographer/src/carto_facade_go/carto_facade.go
> +}
Also lets move all the struct definitions to the top of the file

2023-06-13 19:27 UTC, nicksanford commented on viam-cartographer/src/carto_facade_go/carto_facade.go
> +	// TODO: fill component reference in?
Can we please do this todo?

2023-06-13 19:27 UTC, nicksanford commented on viam-cartographer/src/carto_facade_go/carto_facade.go
> +}
```suggestion
type CartoGetPointCloudMapResponse struct {
	value C.viam_carto_get_point_cloud_map_response
}
```

Lets also move this to the top of the file with the other structs

2023-06-13 19:27 UTC, nicksanford commented on viam-cartographer/src/carto_facade_go/carto_facade.go
> +}
```suggestion
type CartoGetInternalStateResponse struct {
	value C.viam_carto_get_internal_state_response
}
```
Lets move this to the top of the file with the rest of the structs

2023-06-13 19:27 UTC, nicksanford commented on viam-cartographer/src/carto_facade_go/carto_facade.go
> +	return nil, errors.New("unimplemented error")
Can we actually implement this?

2023-06-13 19:27 UTC, nicksanford commented on viam-cartographer/src/carto_facade_go/carto_facade.go
> +	return nil, errors.New("unimplemented error")
Can we actually implement this?

2023-06-22 13:45 UTC, closed without merging