RSDK-2214 remove pre map representation endpoints
viamrobotics/viam-cartographer pull request #29
Opened 2023-03-24 20:50 UTC by JohnN193

removes pre map representation endpoints. All C++ changes are the same as the [previously reverted commit](https://github.com/viamrobotics/viam-cartographer/pull/10), with the addition of changes for the go module.

ticket: https://viam.atlassian.net/browse/RSDK-2214

2023-03-27 18:03 UTC, nicksanford requested changes

2023-03-27 18:03 UTC, nicksanford commented on viam-cartographer_test.go
> +// Package viamcartographer_test tests the functions that require injected components (such as robot and camera)
Why are we adding these tests when the ticket is about removing pre map representation endpoints?

2023-03-27 18:03 UTC, nicksanford commented on viam-cartographer.go
> +package viamcartographer
why is this being added?

2023-03-27 18:11 UTC, jeremyrhyde commented on integration_test.go
> +// Package viamcartographer_test tests the functions that require injected components (such as robot and camera)
[minor] The comment here should be primarily focus on the type of tests this package runs, i.e. integration tests that test the full pipeline from providing fake data from an injected camera to a viam-cartographer binary and hitting the endpoints to confirm proper operation. Addition info such as using the internal package strikes me as superfluous.

2023-03-27 18:13 UTC, jeremyrhyde commented on internal/dim-2d/dim-2d.go
> +// ValidateGetAndSaveData makes sure that the provided sensor is actually a lidar and can
[q] Should the bring-up of a lidar be held in dim-2d as future work in cartographer to support 3D lidars would duplicate much of this. For example the `ValidateGetAndSaveData` would be identical as would the `GetAndSaveData`.

2023-03-27 18:15 UTC, jeremyrhyde commented on internal/dim-2d/dim-2d.go
> +func NewLidar(
[opt] `New2DLidar()`

2023-03-27 18:20 UTC, jeremyrhyde commented on internal/dim-2d/dim-2d.go
> +	pointcloud, err := lidar.GetData(ctx)
[q] Why are we calling `GetData` and not `NextPointCloud` anymore?

2023-03-27 18:21 UTC, jeremyrhyde commented on internal/dim-2d/dim-2d.go
> +func ValidateGetAndSaveData(
Should validation be exposed or unexposed and called by of NewLidar

2023-03-27 18:24 UTC, jeremyrhyde commented on internal/dim-2d/dim-2d_test.go
> +func TestValidateGetAndSaveData(t *testing.T) {
[minor] Can we add a test to check output if a bad lidar is given where say NextPointCloud returns an error as well as any other types of malformed lidars that were created back in out rdk unit tests?

2023-03-27 19:17 UTC, JohnN193 commented
PR went from 17 to 6 files changed, so I declare this actually safe to review now. sorry for the confusion!

2023-03-27 20:48 UTC, JohnN193 commented on go.mod
> +	go.viam.com/utils v0.1.18-0.20230327140716-bfeb34d89117
The only thing I intentionally bumped was rdk, everything else was bumped as a dependency

2023-03-28 11:52 UTC, kkufieta reviewed
Did you test that cartographer still works via RDK & app.viam.com?

2023-03-28 12:52 UTC, JohnN193 commented
Yeah, all c++ code was tested on app. Unsure if I can test the go code at this current state

2023-03-28 14:22 UTC, kkufieta commented
Yes, you can test the go code, and I recommend you do that since you're editing the go code. The steps are:
1. Register the `viam:slam:cartographer` model in RDK by editing services/slam/register/register.go like this:
  ```go
  // Package register registers all relevant slam models and also subtype specific functions
  package register
  
  import (
	  // for slam models.
	  "fmt"
  
	  viamcartographer "github.com/viamrobotics/viam-cartographer"
	  _ "go.viam.com/rdk/services/slam/fake"
  )
  
  func neverUsed() {
	  fmt.Println(viamcartographer.DefaultExecutableName)
  }
  ```
  (in go.mod, replace viam-cartographer with your local viam-cartographer repo path)

2. Change your config by replace `"model": "cartographer"` with `"model": "viam:slam:cartographer"`
3. Run & test cartographer

2023-03-28 14:23 UTC, kkufieta approved these changes
LGTM mod testing the go code via RDK & app.viam.com as described in my comment.

2023-03-28 14:28 UTC, JohnN193 commented
talked offline, I will not be testing the go code by changing my local branch of rdk to recognize it

2023-03-28 14:39 UTC, merged