RSDK-3139 - add slam dependencies into cartographer repo
viamrobotics/viam-cartographer pull request #93
Opened 2023-05-16 19:50 UTC by kim-mishra

2023-05-16 20:03 UTC, nicksanford commented on config/config.go
> +// Warning: The code in this package might be transient. Stability is not guaranteed.
This warning can be removed

2023-05-16 20:04 UTC, EshaMaharishi commented
Removing myself from this review - also, feel free to leave me off PR's for the full modularization project, since Nick is leading the project :)

2023-05-16 20:18 UTC, nicksanford requested changes

2023-05-16 20:18 UTC, nicksanford commented on integration_test.go
> +	vcTesthelper "github.com/viamrobotics/viam-cartographer/testhelper"
could we move `"github.com/viamrobotics/viam-cartographer/testhelper"` into `"github.com/viamrobotics/viam-cartographer/internal/testhelper"`

2023-05-16 20:18 UTC, nicksanford commented on sensors/utils/utils.go
> +// Warning: The code in this package might be transient. Stability is not guaranteed.
can we please remove all the warnings that this package might be transient?

2023-05-16 20:18 UTC, nicksanford commented on sensors/utils/utils.go
> +func GetPNGImage(ctx context.Context, cam camera.Camera) ([]byte, func(), error) {
I don't think this is used

2023-05-16 20:55 UTC, nicksanford commented
Could you please test cartographer manually to confirm that it still behaves as expected after this change & list the manual testing steps you performed in the PR description?

2023-05-18 14:21 UTC, nicksanford approved these changes

2023-05-18 16:18 UTC, merged